# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='tipo',
            field=models.CharField(choices=[('AC', 'Activo'), ('DC', 'Desactivo')], default='AC', max_length=2),
        ),
    ]
